### ISSUE TITLE
[Help] Error while sending torrent: <Fault -506: "Method 'load_raw' not defined"

### ISSUE THREAD

**Issue by therealcorwin** [pymedusa/Medusa#3223]
Hi team,

I create a issue because i'm stuck with my problem and i can't find any solution. After a raid crash on my Synology, i reinstall Medusa and i was unable to send torrent to my seedbox :(. I have this message : 

```
rTorrent: Unable to send Torrent
Error while sending torrent: <Fault -506: "Method 'load_raw' not defined">
```
Before the crash everything worked correctly. Currently, i have no problem with Radarr & Sonarr. And i don't find error on my seedbox. 

I need You ! 👍 

Branch/Commit: 
master /  b16e0e5eb4ded727eebd2ab2cd9683ab597662f5

OS: 
Linux-3.10.105-x86_64-with-glibc2.2.5 (Synology)

Seedbox : 

Debian 9
LIBTORRENT 0.13.6
RTORRENT 0.9.6

What you did: 
Manual and automatic research for series

What happened: 
unable to send torrent to my seedbox

What you expected: 
torrent send to my seedbox

**Logs:**
```
2017-11-03 12:48:44 WARNING  SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] rTorrent: Unable to send Torrent
2017-11-03 12:48:44 WARNING  SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] Error while sending torrent: <Fault -506: "Method 'load_raw' not defined">
2017-11-03 12:48:41 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] Calling rTorrent Client
2017-11-03 12:48:41 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 3.10.105; e2073a3a-bfec-11e7-b02a-0242fa8202c5)
2017-11-03 12:48:41 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] GET URL: https://yggtorrent.com/engine/download_torrent?id=103013 [Status: 200]
2017-11-03 12:48:41 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 3.10.105; e2073a3a-bfec-11e7-b02a-0242fa8202c5)
2017-11-03 12:48:41 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] GET URL: https://yggtorrent.com/ [Status: 200]
2017-11-03 12:48:40 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] With post data: id=**********&submit=&pass=**********
2017-11-03 12:48:40 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 3.10.105; e2073a3a-bfec-11e7-b02a-0242fa8202c5)
2017-11-03 12:48:40 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] POST URL: https://yggtorrent.com/user/login [Status: 200]
2017-11-03 12:48:40 INFO     SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] Downloading Mr.Robot.S03E01.SUBFRENCH.720p.WEB-DL.x264-FDS.mkv with 154 seeders and 0 leechers and size 866.21 MB from Yggtorrent
2017-11-03 12:48:40 INFO     SNATCHQUEUE-MANUALSNATCH-289590 :: [b16e0e5] Beginning to manual snatch release: Mr.Robot.S03E01.SUBFRENCH.720p.WEB-DL.x264-FDS.mkv
```

**Comment by medariox** [comment]
What rTorrent version are you running?

**Comment by therealcorwin** [comment]
Hi @medariox  I just write this info on my post. Sorry for the mistake. 
This is my Seedbox :
Debian 9
LIBTORRENT 0.13.6
RTORRENT 0.9.6

**Comment by medariox** [comment]
That's really strange. I have exactly the same setup and it works just fine here. Can you post a screenshot of your rTorrent config within Medusa? Are you having this issue with any provider or just with some?

**Comment by therealcorwin** [comment]
Yes very strange .... With Sonarr & Radarr it's works like a charm. Now with medusa no :( I dont understand .... 

My configuration : https://www.dropbox.com/s/2et4v4f96zkm6cj/Medusa.PNG

**Comment by medariox** [comment]
Don't know how to help, sorry. Same OS, rTorrent and libtorrent version here and it works as expected. Seems more like an issue with rTorrent though, `load_raw` method is not callable?

**Comment by therealcorwin** [comment]
Arfff :( How can i check That ? 
In the worst case, I can give you access to the seedbox to investigate. I master not very well the calls RPC and html.

**Comment by medariox** [comment]
Can you please try [this branch](https://github.com/pymedusa/Medusa/tree/fix-rtorrent-0.9.6) and report back?

**Comment by therealcorwin** [comment]
Thx for the branch 👍  installation is on progress

**Comment by therealcorwin** [comment]
Sorry for the delay, some problems with Git :/ 

So, Good news and Bad News. 

Good News : 
My seedbox received correctly the torrent :1 

Bad News : 
2017-11-07 15:10:41 WARNING  SNATCHQUEUE-MANUALSNATCH-289590 :: [48f4968] rTorrent: Unable to send Torrent
2017-11-07 15:10:41 WARNING  SNATCHQUEUE-MANUALSNATCH-289590 :: [48f4968] Error while sending torrent: MethodError()
2017-11-07 15:10:38 DEBUG    SNATCHQUEUE-MANUALSNATCH-289590 :: [48f4968] Calling rTorrent Client
The torrent is in download queue on my seedbox, but have the status "stop" and have no label (The label is "Serie" in Medusa parameters. I need to start the download with a manual action. 

I have this error at Medusa starting, but this is not the purpose of this issue. 
ERROR:stevedore.extension:Could not load 'subscenter': No module named subscenter
ERROR:stevedore.extension:Could not load 'thesubdb': The 'six>=1.9.0' distribution was not found and is required by the application
/usr/local/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.130)
/usr/local/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.130)

**Comment by therealcorwin** [comment]
My problem look like this one : https://github.com/SickRage/SickRage/issues/2934 ? No ?

**Comment by medariox** [comment]
No, just a mistake on my part. Please update the branch, it should work now.

**Comment by therealcorwin** [comment]
Same problem :( 

Medusa Info: | Branch: Commit: 382de1e99273df9a12dc3aef5d9cdd9c914d6e7f

What git  command i need to use to update my local branch. Each time i have tousand problems to update :(

**Comment by medariox** [comment]
`cd` to your main Medusa folder (usually `medusa`)
`git checkout fix-rtorrent-0.9.6`
`git pull`

**Comment by therealcorwin** [comment]
I just fund the cause of my problem on my git. i'm not an expert :D The problem is still present even if i made a proper update.

**Comment by medariox** [comment]
So the torrent is added, but it's paused and without label now?

**Comment by therealcorwin** [comment]
Yes, torrent added but stoped and no label.

With method erreur in debug log. See my previous post.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by therealcorwin** [comment]
Hi Medariox,

Have you some good news for me ? :)

**Comment by medariox** [comment]
@therealcorwin 
Not yet! Will have another try today.

**Comment by therealcorwin** [comment]
@medariox
Cool ! I would be available to test it :)

**Comment by medariox** [comment]
That's great! Can you update the branch and try again, please?

**Comment by therealcorwin** [comment]
I have 2 errors : 

rTorrent: Unable to send Torrent
Error while sending torrent: MethodError()
Calling rTorrent Client
User-Agent: Medusa/0.0.1 (Linux; 3.10.105; a8d3f3f8-cc63-11e7-ba50-0242a0f15990)
GET URL: https://yggtorrent.com/engine/download_torrent?id=106964 [Status: 200]
User-Agent: Medusa/0.0.1 (Linux; 3.10.105; a8d3f3f8-cc63-11e7-ba50-0242a0f15990)

The torrent have the status "download" but no label :( 


And a the new one : 

[Yggtorrent] :: [7978df5] Fallback season pack search initiate
[Yggtorrent] :: [7978df5] Failed parsing provider.
Traceback (most recent call last):
  File "/volume2/Medusa/medusa/providers/torrent/html/yggtorrent.py", line 127, in parse
    download_url = urljoin(self.url, cells[0].find('a', target='_blank')['href'])
TypeError: 'NoneType' object has no attribute '__getitem__'

But this one come from the new version of the site, may be.

**Comment by medariox** [comment]
Please let's stick to one issue. The second one is related to the recent changes to yggtorrent, you can open a new issue for that one if you want.

So, the torrent is starting correctly now but is missing the label?

**Comment by therealcorwin** [comment]
Sorry for the delay. 

MY torrent had the status download but it not download nothing. Problem solved , flus my DNS cache

So, Yes the download works well but no label.

**Comment by medariox** [comment]
Please update and try again.

**Comment by therealcorwin** [comment]
no change :( 

Branch: fix-rtorrent-0.9.6
Commit: 4b5df0df1c15ffb84db996bbe27b0d8563029d70
--

**Comment by medariox** [comment]
One more try?

**Comment by therealcorwin** [comment]
doesn't works. 

I just seen that the episode doesn't have the status "snatched" in Medusa. But it's may be a side effect of error. 

Branch: fix-rtorrent-0.9.6
Commit: 9b75e0f0abc971e6613d27ee3b09b07173de64e7

**Comment by medariox** [comment]
What error?

**Comment by therealcorwin** [comment]
The MEthodError
9b75e0f] rTorrent: Unable to send Torrent
9b75e0f] Error while sending torrent: MethodError()

**Comment by medariox** [comment]
I think something went wrong with your pull, you shouldn't get that error. Try to pull again.

**Comment by therealcorwin** [comment]
I re-pull your branch, and I have the same error :/ 

Error while sending torrent: MethodError()
rTorrent: Unable to send Torrent

I reinstalling from scratch Medusa, to see if something change after the reinstall. 

Branch: fix-rtorrent-0.9.6
Commit: 9c26090a67ed0090a744a978bac7687b895f6116

**Comment by medariox** [comment]
Related: https://github.com/Sonarr/Sonarr/issues/1745

That means that a (at least) partial rewrite of the rtorrent lib will be needed.

**Comment by p0psicles** [comment]
Or maybe consider switching to transmission?

**Comment by therealcorwin** [comment]
@medariox : Arf :/ auto download works thanks to your modification but label not. I don't know why before it's works like a charm and today not :( 

@p0psicles : I'm not against the switch. I use all in one script to create my seedbox and it administration but i don't know how works transmission. If you can't resolve this problem, I am going to have to rewrite the script completely. That is why I preferred to keep rtorrent :)

**Comment by renini** [comment]
I have the same errors with the fix-rtorrent-0.9.6 branch
`2017-11-23 21:22:46 WARNING  SEARCHQUEUE-BACKLOG-153021 :: [9c26090] Error while sending torrent: MethodError()`
`2017-11-23 21:22:46 WARNING  SEARCHQUEUE-BACKLOG-153021 :: [9c26090] rTorrent: Unable to send Torrent`

will try to debug this tomorrow, might this be related to the rtorrent command changes?
https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP)

for example **execute_raw** is now **execute.raw**

**Comment by therealcorwin** [comment]
@renini the branch "fix-rtorrent-0.9.6", for me,  fix the sending & auto start download problem. But the label doesn't work yet. And in Medusa, when a torrent is downloading, the episode doesn't have the status "Snatched"

I am available to test :)

**Comment by medariox** [comment]
Please update branch `fix-rtorrent-0.9.6` and report back.

**Comment by renini** [comment]
Works!!!! The torrent was downloaded and the label is set! @medariox thanks! you rock

**Comment by therealcorwin** [comment]
the error is still here : 
[b1bf495] Calling rTorrent Client
[b1bf495] Error while sending torrent: MethodError()
[b1bf495] rTorrent: Unable to send Torrent

But the torrent have his label :) In medusa, the episode doesn't have the status "snatched".

Good work ! we progress :) 

Branch: fix-rtorrent-0.9.6
Commit: b1bf4955e8132f5d6bfff45aea453269a5ef03b8
Version: v0.1.17

**Comment by renini** [comment]
yeh same thing for me, it still reports the error, but the torrent + label gets downloaded.
Status is still on wanted instead of snatched indeed...

**Comment by medariox** [comment]
Thanks for the feedback, we are almost there!
One more update and report back.

**Comment by renini** [comment]
Now i get this:
[206602b] rTorrent: Unable to send Torrent
[206602b] Error while sending torrent: AttributeError("Torrent instance has no attribute 'hashing'",)

**Comment by therealcorwin** [comment]
This time, i have this error : 
Calling rTorrent Client
 Error while sending torrent: AttributeError("Torrent instance has no attribute 'hashing'",)
Torrent: Unable to send Torrent

Branch: fix-rtorrent-0.9.6
Commit: 206602b67f0104d6fda7cce8440556398ba424cb
Version: v0.1.17

**Comment by medariox** [comment]
So close! One more time please.

**Comment by therealcorwin** [comment]
Same error :( 

Branch: fix-rtorrent-0.9.6
Commit: 6cdf834fb2b519cfdbd7a88905018e8cc8e7d745
Version: v0.1.17

**Comment by medariox** [comment]
🦀 Aaaaand one more time please.

**Comment by therealcorwin** [comment]
Same player, play again :) 

Same error :/ 

Branch: fix-rtorrent-0.9.6
Commit: 8bf7bd725835913061b7088c0887952bc9b3b39d
Version: v0.1.17

**Comment by medariox** [comment]
Weird, should be working... try now please.

**Comment by therealcorwin** [comment]
No change :( 
Calling rTorrent Client
Error while sending torrent: AttributeError("Torrent instance has no attribute 'state'",)
rTorrent: Unable to send Torrent

One question , in manual search i see some choice of torrent with pink color. What does't it mean ?

Branch: fix-rtorrent-0.9.6
Commit: 62125d6596f7dc8f38d121cd5923f488063f6e60
Version: v0.1.17

**Comment by renini** [comment]
Same thing for me:
[62125d6] rTorrent: Unable to send Torrent
[62125d6] Error while sending torrent: AttributeError("Torrent instance has no attribute 'state'",)

Do you need more debugging output from the actually http request?

**Comment by medariox** [comment]
Nope, just update and let me know please.

**Comment by therealcorwin** [comment]
A little evolution : 

 Error while sending torrent: AttributeError("Torrent instance has no attribute 'name'",)


Branch: fix-rtorrent-0.9.6
Commit: 06521b96caffb22e087418b18ae7d361006e8ed4
Version: v0.1.17

**Comment by medariox** [comment]
Update + report, thanks!

**Comment by therealcorwin** [comment]
Sir, Yes Sir !
________________________________

**Comment by therealcorwin** [comment]
Hummm, Sounds Good :) 
Well Done ! :v::v:

Torrent auto download + Label + Status "Snatched"

**Comment by renini** [comment]
Awesomeness! seems to work here too! I should get you 🍺 

Thanks!

**Comment by medariox** [comment]
Great to hear guys! Sadly there is still a lot to do before the changes can be pushed to develop. I could really use your help in the coming days for some other tests. 👍

**Comment by therealcorwin** [comment]
No problem, i am available to test. Just let me know When a new commit is pushed on github.

And a huge thx for all the time you spend on Medusa ! :clap::clap:

**Comment by medariox** [comment]
@therealcorwin @renini 
Can you update the branch and give some feedback, please? If all goes well I will open a PR to merge the changes.

**Comment by therealcorwin** [comment]
@medariox I just update Medusa from gui and it is unavailable just after the update. I'm not am home yet, i check that  in one hour

**Comment by renini** [comment]
@medariox i shutdown the service, git pull to update and started again. 
Changed an episode to wanted, and i got snatched and downloaded.
So for me it still seems to work :+1: 

2017-11-28 14:57:00 INFO     TORNADO :: [2f5ef17] User logged into the Medusa web interface

**Comment by therealcorwin** [comment]
This is error who crashed medusa at restart : 

2017-11-28 13:58:12 INFO     Thread-18 :: [2f5ef17] AttributeError: 'module' object has no attribute 'LAYOUT_WIDE'
2017-11-28 13:58:13 INFO     EVENT-QUEUE :: [2f5ef17] Shutting down Tornado
2017-11-28 13:58:13 ERROR    Thread-18 :: [2f5ef17] Exception generated: 'module' object has no attribute 'LAYOUT_WIDE'
Traceback (most recent call last):
  File "/volume2/Medusa/medusa/server/web/core/base.py", line 258, in async_call
    if len(value) == 1:
  File "/volume2/Medusa/medusa/server/web/home/handler.py", line 728, in update
    controller='home', action='restart')
  File "/volume2/Medusa/medusa/server/web/core/base.py", line 136, in render
    for (filename, lineno, function, _) in kwargs['backtrace'].traceback:
  File "/volume2/Medusa/ext/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/volume2/Medusa/ext/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/volume2/Medusa/ext/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/volume2/Medusa/ext/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/volume2/Medusa/cache/mako/layouts/main.mako.py", line 108, in render_body
AttributeError: 'module' object has no attribute 'LAYOUT_WIDE'
2017-11-28 13:58:13 INFO     EVENT-QUEUE :: [2f5ef17] Restarting Medusa with ['/bin/python2.7', u'/volume2/Medusa/start.py', '--nolaunch']
2017-11-28 13:58:14 ERROR    EVENT-QUEUE :: [2f5ef17] Exception generated in thread EVENT-QUEUE: error 5 : Input/output error
Traceback (most recent call last):
  File "/volume2/Medusa/medusa/event_queue.py", line 51, in run
    self.callback(event_type)
  File "/volume2/Medusa/medusa/__main__.py", line 2091, in shutdown
    finally:
  File "/volume2/Medusa/medusa/__main__.py", line 2010, in restart
    # shutdown the logger to make sure it's released the logfile BEFORE it restarts SR.
IOError: [Errno 5] Input/output error
2017-11-28 13:58:14 DEBUG    EVENT-QUEUE :: [2f5ef17] 'Traceback (most recent call last):\n  File "/volume2/Medusa/medusa/event_queue.py", line 51, in run\n    self.callback(event_type)\n  File "/volume2/Medusa/medusa/__main__.py", line 2091, in shutdown\n    finally:\n  File "/volume2/Medusa/medusa/__main__.py", line 2010, in restart\n    # shutdown the logger to make sure it\'s released the logfile BEFORE it restarts SR.\nIOError: [Errno 5] Input/output error\n'

After a manual restart, it works fine. I download 4 episodes and no problem

**Comment by medariox** [comment]
Thanks a lot for the help guys, we did it! The PR is now open and will be merged to develop soon: https://github.com/pymedusa/Medusa/pull/3333

**Comment by therealcorwin** [comment]
Huge Thx to you for your great work :)

**Comment by renini** [comment]
@medariox again many thanks for your work on this! One question, i see it got merged to develop now and the branch is deletec, should i swtich to the develop branch:

```
git checkout develop
git pull
```

like so? or should i do something else to keep using this fixed version

**Comment by medariox** [comment]
@renini 
Exactly 👌

**Comment by therealcorwin** [comment]
Hi @medariox 
I have bad news :( the error is back on master branch ;( 
@renini , have you the error too ? 

LOG : 
[1a8dc66] uTorrent: Unable to send Torrent
[1a8dc66] uTorrent: Method Not Allowed
[1a8dc66] With post data: -dd68d43f00be4147afa4d53c56b42121
 Content-Disposition: form-data; name="torrent_file"; filename="...
[1a8dc66] User-Agent: Medusa/0.1.20 (Linux; 3.10.105; af719f4c-dacf-11e7-a650-0242a0f15990)
[1a8dc66] POST URL: https://plop.com/rutorrent/plugins/httprpc/gui/?token=+%3Ccanvas+id%3D%22movemonkey%22+width%3D%22312%22+height%3D%22312%22%3E&action=add-file [Status: 405]
[1a8dc66] uTorrent: Requested a POST connection to https://plop.com/rutorrent/plugins/httprpc/gui/ with params: OrderedDict([(u'token', u' <canvas id="movemonkey" width="312" height="312">'), (u'action', u'add-f... Data: None
[1a8dc66] User-Agent: Medusa/0.1.20 (Linux; 3.10.105; af719f4c-dacf-11e7-a650-0242a0f15990)
[1a8dc66] GET URL: https://plop.com/rutorrent/plugins/httprpc/gui/token.html [Status: 200]
[1a8dc66] Calling uTorrent Client

Branch: master
Commit: 1a8dc66c7ec9231be0d3444710e476437c9ae1c8
Version: v0.1.20

**Comment by medariox** [comment]
@therealcorwin 
That's really strange... I just merged the changes to master after you confirmed it was working.

**Comment by renini** [comment]
@therealcorwin i'm still on the develop branch and that one still works for me.

**Comment by renini** [comment]
@therealcorwin why does your log say uTorrent instead of rtorrent?

**Comment by medariox** [comment]
Good catch @renini, that's probably the issue then.

**Comment by renini** [comment]
@therealcorwin I just switched to the master branch, and mine is still working. 👍 Before i tested i doubled checked that the Search settings -> Torrent search was set to rTorrent, to make sure I selected uTorrent, then switched back to rTorrent and clicked save changes.

**Comment by therealcorwin** [comment]
@medariox @renini 

Hum hum.... how to say that .... :o) My bad ! When i reconfigured Medusa, icheck too fast a provider and i use utorrent instead of rtorrent -_- 

Sorry for this inconvience 👼
