### ISSUE TITLE
Download Station (Synology) doesn't receive the .torrent file

### ISSUE THREAD

**Issue by pucelano7** [pymedusa/Medusa#3460]
**OS:** DSM 6.1.4-15217 Update 2 (NAS Synology DS213)
**What you did:** I have installed Medusa recently and I am configuring it
**What happened:** when Medusa find a TV Show with the status "Wanted" it searches the .torrent file and sends it to "Download Station". 
Always I receive a notification in my phone but when I check it Sometimes Download Station doesn't receive the .torrent file (but sometimes it works fine...I don't understand it) 
**Logs:** An example:
```
2017-12-13 13:12:48 ERROR    SEARCHQUEUE-BACKLOG-274431 :: [1a8dc66] DownloadStation: Unknown exception raised when send torrent to DownloadStation : ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/clients/torrent/generic.py", line 76, in _request
    cookies=cookies, timeout=120, verify=False)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/session/core.py", line 94, in request
    **kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/requests/sessions.py", line 658, in send
    r.content
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

![medusa](https://user-images.githubusercontent.com/24883267/33940057-defdcd1a-e00d-11e7-8481-ec291b6e1253.jpg)

**Comment by fernandog** [comment]
@pucelano7 maybe connection was lost while sending torrent? As error: 'Connection broken: IncompleteRead

**Comment by pucelano7** [comment]
@fernandog yes, maybe this was the problem

**Comment by medariox** [comment]
Please reopen if it happens again.

**Comment by kicker83** [comment]
I have the same problem.

`2018-12-04 11:43:33 ERROR    SNATCHQUEUE-SNATCH-350071 :: [54da0c7] DownloadStation: Unknown exception raised when send torrent to DownloadStation : ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Traceback (most recent call last):
  File "/app/medusa/medusa/clients/torrent/generic.py", line 82, in _request
    cookies=cookies, timeout=120, verify=False)
  File "/app/medusa/medusa/session/core.py", line 102, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 686, in send
    r.content
  File "/app/medusa/ext/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/app/medusa/ext/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))`

**Comment by kicker83** [comment]
I think is an encoding problem. Look at this logs, please:

This snatched episode was completed succesfully:
`2018-12-04 15:27:15 INFO     SNATCHQUEUE-SNATCH-43 :: [54da0c7] Downloading Outlander.4x05.Salvajes.WEBRip.1080p.Dual.Ac3.[HDT.Series].[spanish] with 6 seeders and 8 leechers and size 3.35 GB from HDCity, through a SearchType.BACKLOG_SEARCH search`

But this episode had the DownloadStation problem:
`SNATCHQUEUE-SNATCH-73762 :: [54da0c7] Downloading Anatomia.de.Grey.15x07.��Tiene.alguien.un.mapa��.[WEB-DL.AMZN.1080p.h264.Dual.DD.2.0-5.1.Sub][ShareRip-GrupoHDS].[spanish] with 61 seeders and 61 leechers and size 1.79 GB from HD-Spain, through a SearchType.MANUAL_SEARCH search`

**Comment by medariox** [comment]
@kicker83 
Please replace this line: https://github.com/pymedusa/Medusa/blob/master/medusa/clients/torrent/downloadstation_client.py#L145
with this code:
```
torrent_name = b''.join([result.name.encode('utf-8'), b'.torrent'])
files = {'file': (torrent_name, result.content)}
```

Restart Medusa and try to snatch the same torrent again. Let me know if it works.

**Comment by kicker83** [comment]
> @kicker83
> Please replace this line: https://github.com/pymedusa/Medusa/blob/master/medusa/clients/torrent/downloadstation_client.py#L145
> with this code:
> 
> ```
> torrent_name = b''.join([result.name.encode('utf-8'), b'.torrent'])
> files = {'file': (torrent_name, result.content)}
> ```
> Restart Medusa and try to snatch the same torrent again. Let me know if it works.

Thanks so much!, Now the encoding is working perfect, but the question marks in title are problematic:

Anatomia de Grey 15x07 ¿Tiene alguien un mapa¿ [WEB-DL AMZN 1080p h264 Dual DD 2.0-5.1 Sub][ShareRip-GrupoHDS]

`SNATCHQUEUE-SNATCH-73762 :: [54da0c7] Downloading Anatomia.de.Grey.15x07.��Tiene.alguien.un.mapa��.[WEB-DL.AMZN.1080p.h264.Dual.DD.2.0-5.1.Sub][ShareRip-GrupoHDS].[spanish] with 77 seeders and 77 leechers and size 1.79 GB from HD-Spain, through a SearchType.MANUAL_SEARCH search`

**Comment by medariox** [comment]
Don't worry about that, it's just a logging (visual) problem. It should be fixed with the next release.
Is the snatch issue with Download Station fixed for you now?

**Comment by kicker83** [comment]
> Don't worry about that, it's just a logging (visual) problem. It should be fixed with the next release.
> Is the snatch issue with Download Station fixed for you now?

No, is not only for the logging, if there are question marks in title, medusa is not able to send torrent to DownloadStation. Same error log:

`SNATCHQUEUE-SNATCH-73762 :: [54da0c7] DownloadStation: Unknown exception raised when send torrent to DownloadStation : ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))`

Thanks

**Comment by kicker83** [comment]
It fixed por example this:

"Black Lightning - S02E08 - El Libro de la Rebelión Capítulo Uno"

I don't know what is happening with this kind of titles. I'm going to test another titles and I'll tell you the results. 

"Anatomia de Grey 15x07 ¿Tiene alguien un mapa¿ [WEB-DL AMZN 1080p h264 Dual DD 2.0-5.1 Sub][ShareRip-GrupoHDS]"

Thanks!!

**Comment by kicker83** [comment]
Nah, my fault, I thougtht the problem has been solved but it doesn't. I still get the same error, for example with this episode:

The Flash 5x04 Noticias rápidas 1080p WEB-DL 1080p Dual Ac3+Sub [HDT Series] 

As you can see there is an "á". If I try to snatch this episode:

The Flash 5x03 La muerte de Vibe WEB DL 1080p Dual Ac3+Sub [HDT Series]

Is working perfect.

Thanks!!

**Comment by kicker83** [comment]
I've been trying some changes, but I still getting same error. In synology logs I see this:

`2018-12-11T10:47:21+01:00 Syno task.cgi: synoupload.c:818 failed to check whether contains boundary --6eb0f4be88a35c19f5e0bf17173b7224 from ▒k▒▒▒▒▒:Fd▒f▒G▒#
.虄▒▒▒j▒▒▒▒▒▒F+Ů▒̈▒폤|N▒▒]U▒▒8▒▒▒▒
▒n▒x▒߅▒)▒(k9!▒▒▒G▒9▒▒▒▒!▒▒sM(<▒▒▒*▒▒)@▒`09K▒▒@▒:▒lPZd▒.▒ah*▒▒r`▒
}[;u▒ɲ▒▒؛ߩ%▒▒O▒*DG▒▒▒▒s:▒t,▒▒ݕ▒U▒
▒▒!▒▒▒
      ▒MO▒G
2018-12-11T10:47:21+01:00 Syno task.cgi: synoupload.c:1165 failed to load params
2018-12-11T10:47:21+01:00 Syno task.cgi: WebCGI.cpp:510 failed to upload to path /volume1/@tmp
2018-12-11T10:47:21+01:00 Syno task.cgi: task.cpp:309 Failed to upload file -9
`

**Comment by medariox** [comment]
Ping if this is still an issue.
