### ISSUE TITLE
Medusa suddenly not grabbing new Boku no Hero Academia episodes

### ISSUE THREAD

**Issue by JHBoricua** [pymedusa/Medusa#7627]
**Describe the bug**
Since last week (starting with episode 77, aka Season 4 episode 14), Medusa has failed to grab episodes from Boku no Hero Academia. Even if I  download the episode manually and place it in the folder Medusa processes from, it fails to recognize the downloaded file as the wanted episode and thus it won't process it. The naming of the episodes has not changed. I'm pasting the output of the logs from this morning when I did a forced search of Episode 78 (S04E15), which is out already at Nyaa. Medusa sees the torrents from HorribleSubs but won't grab it. I'm trying to understand why it is failing to do so.

**Medusa (please complete the following information):**
 - OS: Centos
 - Branch: master
 - Commit: 942040af95311a71d9663236c7136434b6711ca5 
 - Python version: 3.7.4
 - Database version: 44.14

**Debug logs (at least 50 lines):**
```
2020-01-25 12:57:55 INFO	FORCEDSEARCHQUEUE-BACKLOG-305074 :: [942040a] No needed episodes found during backlog search for: My Hero Academia
2020-01-25 12:57:55 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: [942040a] No results to sort.
2020-01-25 12:57:55 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: [942040a] Combining single and multi-episode results
2020-01-25 12:57:55 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Found 0 unique search results
2020-01-25 12:57:55 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:55 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:55 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=Boku+no+Hero+Academia+4th+Season+15 [Status: 200]
2020-01-25 12:57:50 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:50 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: Boku no Hero Academia 4th Season 15
2020-01-25 12:57:50 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:50 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:50 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=Boku+no+Hero+Academia+78 [Status: 200]
2020-01-25 12:57:44 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:44 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: Boku no Hero Academia 78
2020-01-25 12:57:44 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:44 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:44 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=My+Hero+Academia+4th+Season+15 [Status: 200]
2020-01-25 12:57:39 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:39 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: My Hero Academia 4th Season 15
2020-01-25 12:57:39 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:39 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:39 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=Boku+no+Hero+Academia+S4+15 [Status: 200]
2020-01-25 12:57:34 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:34 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: Boku no Hero Academia S4 15
2020-01-25 12:57:34 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:34 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:34 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=My+Hero+Academy+S4+15 [Status: 200]
2020-01-25 12:57:29 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:29 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: My Hero Academy S4 15
2020-01-25 12:57:29 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:29 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:29 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=My+Hero+Academia+S4+15 [Status: 200]
2020-01-25 12:57:24 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:24 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: My Hero Academia S4 15
2020-01-25 12:57:24 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:24 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:24 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=My+Hero+Academia+78 [Status: 200]
2020-01-25 12:57:19 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:19 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: My Hero Academia 78
2020-01-25 12:57:19 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] No results found Code: 20
2020-01-25 12:57:19 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:19 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] GET URL: http://torrentapi.org/pubapi_v2.php?app_id=medusa&category=tv&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=xu2pyjlni9&sort=seeders&mode=search&search_tvdb=305074&search_string=Boku+No+Hero+Academia+%282019%29+15 [Status: 200]
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Searching only ranked torrents
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search string: Boku No Hero Academia (2019) 15
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Search mode: Episode
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Could not find any candidates in cache, searching provider.
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Transaction with 1 queries executed
2020-01-25 12:57:13 INFO	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Rarbg :: [942040a] Performing episode search for My Hero Academia
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Transaction with 5 queries executed
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] We aren't interested in this result: [HorribleSubs].Boku.no.Hero.Academia.-.78.[480p].mkv with url: https://nyaa.si/download/1215046.torrent
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Updating item: [HorribleSubs].Boku.no.Hero.Academia.-.78.[480p].mkv to cache: nyaa
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Adding item from search to cache: '[HorribleSubs].Boku.no.Hero.Academia.-.78.[480p].mkv'
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] We aren't interested in this result: [HorribleSubs].Boku.no.Hero.Academia.-.78.[720p].mkv with url: https://nyaa.si/download/1215047.torrent
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Updating item: [HorribleSubs].Boku.no.Hero.Academia.-.78.[720p].mkv to cache: nyaa
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Adding item from search to cache: '[HorribleSubs].Boku.no.Hero.Academia.-.78.[720p].mkv'
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] We aren't interested in this result: [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[720p][C3ED620B].mkv with url: https://nyaa.si/download/1215117.torrent
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Updating item: [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[720p][C3ED620B].mkv to cache: nyaa
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Adding item from search to cache: '[PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[720p][C3ED620B].mkv'
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] We aren't interested in this result: [HorribleSubs].Boku.no.Hero.Academia.-.78.[1080p].mkv with url: https://nyaa.si/download/1215050.torrent
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Updating item: [HorribleSubs].Boku.no.Hero.Academia.-.78.[1080p].mkv to cache: nyaa
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Adding item from search to cache: '[HorribleSubs].Boku.no.Hero.Academia.-.78.[1080p].mkv'
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] We aren't interested in this result: [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[1080p][3B99299F].mkv with url: https://nyaa.si/download/1215115.torrent
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Updating item: [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[1080p][3B99299F].mkv to cache: nyaa
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Adding item from search to cache: '[PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[1080p][3B99299F].mkv'
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] The result [HorribleSubs].Boku.no.Hero.Academia.-.78.[480p].mkv doesn't seem to match an episode that we are currently trying to snatch, skipping it
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Using cached parse result for [HorribleSubs].Boku.no.Hero.Academia.-.78.[480p].mkv
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] The result [HorribleSubs].Boku.no.Hero.Academia.-.78.[720p].mkv doesn't seem to match an episode that we are currently trying to snatch, skipping it
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Using cached parse result for [HorribleSubs].Boku.no.Hero.Academia.-.78.[720p].mkv
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] The result [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[720p][C3ED620B].mkv doesn't seem to match an episode that we are currently trying to snatch, skipping it
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Using cached parse result for [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[720p][C3ED620B].mkv
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] The result [HorribleSubs].Boku.no.Hero.Academia.-.78.[1080p].mkv doesn't seem to match an episode that we are currently trying to snatch, skipping it
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Using cached parse result for [HorribleSubs].Boku.no.Hero.Academia.-.78.[1080p].mkv
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] The result [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[1080p][3B99299F].mkv doesn't seem to match an episode that we are currently trying to snatch, skipping it
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Using cached parse result for [PuyaSubs!].Boku.no.Hero.Academia.4th.Season.-.78.[1080p][3B99299F].mkv
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Found 5 unique search results
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=Boku+no+Hero+Academia+4th+Season+15 [Status: 200]
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: Boku no Hero Academia 4th Season 15
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Discarding torrent because it doesn't meet the minimum seeders: [PuyaSubs!] Boku no Hero Academia 3 - 40 [720p][D787D7A4].mkv. Seeders: 0
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Found result: [HorribleSubs] Boku no Hero Academia - 78 [480p].mkv with 1081 seeders and 259 leechers
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Found result: [HorribleSubs] Boku no Hero Academia - 78 [720p].mkv with 3112 seeders and 485 leechers
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Found result: [HorribleSubs] Boku no Hero Academia - 78 [1080p].mkv with 4979 seeders and 654 leechers
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Found result: [PuyaSubs!] Boku no Hero Academia 4th Season - 78 [1080p][3B99299F].mkv with 160 seeders and 43 leechers
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Found result: [PuyaSubs!] Boku no Hero Academia 4th Season - 78 [720p][C3ED620B].mkv with 97 seeders and 34 leechers
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:13 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=Boku+no+Hero+Academia+78 [Status: 200]
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: Boku no Hero Academia 78
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=My+Hero+Academia+4th+Season+15 [Status: 200]
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: My Hero Academia 4th Season 15
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:12 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=Boku+no+Hero+Academia+S4+15 [Status: 200]
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: Boku no Hero Academia S4 15
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=My+Hero+Academy+S4+15 [Status: 200]
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: My Hero Academy S4 15
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:11 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=My+Hero+Academia+S4+15 [Status: 200]
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: My Hero Academia S4 15
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=My+Hero+Academia+78 [Status: 200]
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: My Hero Academia 78
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Data returned from provider does not contain any confirmed torrents
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] User-Agent: Medusa/0.3.10 (Linux; 5.0.21-5-pve; 33ce3e18-3fa4-11ea-b83e-ba17792f274e)
2020-01-25 12:57:10 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] GET URL: https://nyaa.si/?page=rss&c=1_0&f=2&q=Boku+No+Hero+Academia+%282019%29+15 [Status: 200]
2020-01-25 12:57:09 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search string: Boku No Hero Academia (2019) 15
2020-01-25 12:57:09 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Searching only confirmed torrents
2020-01-25 12:57:09 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Search mode: Episode
2020-01-25 12:57:09 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Could not find any candidates in cache, searching provider.
2020-01-25 12:57:09 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Transaction with 1 queries executed
2020-01-25 12:57:09 INFO	FORCEDSEARCHQUEUE-BACKLOG-305074 :: Nyaa :: [942040a] Performing episode search for My Hero Academia
```
**Additional context**

**Comment by medariox** [comment]
The episode is not set to Wanted because according to the indexers information it is not aired yet. Either wait for the next backlog search or set it manually to Wanted, otherwise it won't be snatched.

**Comment by JHBoricua** [comment]
The episode was set to wanted. Which indexer information are you referring to? The airdate was showing correctly in Medusa as today 1/25 @ 2:30 AM. The log output above is from a forced search in order to post the issue here as it was not snatching the episode during the normal search cycle.

**Comment by p0psicles** [comment]
What's your show config?

**Comment by medariox** [comment]
Maybe the show is not up to date with the indexer, try a full update.

**Comment by p0psicles** [comment]
I also watch that show. Works fine here. Also the nyaa releases. It should snatch during a daily search in 99% of the time

**Comment by JHBoricua** [comment]
Hey p0psicles, the show is setup with 720p for quality, anime flag enabled and HorribleSubs in the Release Group whitelist. That's all. 

Been working fine until episode 77 (S04E14) came out last week. Medusa wouldn't snatch it despite the debug output showing the torrent being available. Yesterday was the same with episode 78. I'll wait for next week's release to see what happens. Medusa has been rock solid so far so I'm not understanding why it's not seeing the torrent as a valid one. I'll do a full update next Friday night before the next episode releases and see what happens the next morning.

**Comment by p0psicles** [comment]
Can you post screenshots of the shows displayShow page? Also any min seeders / verified only config in providers config.?

**Comment by MakhouT** [comment]
I am having the same issue.

**Comment by mrmarino** [comment]
Same issue here. Here it seems to be ignoring absolute numbering and only searching for S04EXX. When i downloaded the torrent directly, medusa thought it was S01E77.

**Comment by medariox** [comment]
![imgg](https://snapr.pw/i/264950126f.png)

How hard can it be to run a manual search and post the relevant debug logs?

**Comment by mrmarino** [comment]
Here it is, sunshine.

![image](https://user-images.githubusercontent.com/1873061/73216606-0cada480-4135-11ea-9a4e-e45d71dbd439.png)

> 2020-01-27 18:43:48 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: BTDB :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:43:42 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: Zooqle :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:43:40 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: AniDex :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:43:35 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: TokyoToshokan :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:43:30 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: Nyaa :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:43:13 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: Torrentz2 :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:43:04 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: LimeTorrents :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:42:32 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: ThePirateBay :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:41:50 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: Rarbg :: [942040a] Performing episode search for My Hero Academia
> 2020-01-27 18:41:50 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: [942040a] Using manual search providers
> 2020-01-27 18:41:50 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: [942040a] Building internal name cache for My Hero Academia
> 2020-01-27 18:41:50 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: [942040a] Finished processing 3276 scene exceptions.
> 2020-01-27 18:41:50 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: [942040a] Updating exception_cache and exception_season_cache
> 2020-01-27 18:41:50 INFO	FORCEDSEARCHQUEUE-MANUAL-305074 :: [942040a] Beginning manual search for: My Hero Academia - S04E15 - Smoldering Flames

Proof that "anime" is selected on show config:

![image](https://user-images.githubusercontent.com/1873061/73216695-39fa5280-4135-11ea-871e-b3b8f1197280.png)

**Comment by mrmarino** [comment]
Pastebin debug logs after restart.

https://pastebin.com/x3Lif5TH

**Comment by medariox** [comment]
And you also expect support now after calling me that? Good luck!

**Comment by mrmarino** [comment]
I just came here to confirm that me and @JHBoricua had the same issue, so it's not looking like "misconfiguration". My response was in the same tone you had when you requested the information.

If we can calm down a bit, I'm more than happy to provide more information. Seems like the bug was introduced last release with PR #7577 ?

**Comment by medariox** [comment]
If I ask for that information is because I need it and not to because I want to waste your time. We always ask for debug logs and a manual search and it is almost never posted. I have the right to be annoyed about that, yes. You have no right to be cocky about getting free software and free support.

Now that we have that cleared up: this bug is already fixed in develop, so either switch branch or just wait for the new release. No, there is no ETA for the new release.

**Comment by mrmarino** [comment]
You have every right to be annoyed, but I see no reason to be a dick.

Nevertheless, thank you very much for your efforts.

**Comment by JHBoricua** [comment]
Thanks Medariox. For the record, I did post the debug logs of a manual search in my opening post.

**Comment by medariox** [comment]
@JHBoricua 
That's a forced backlog search.

**Comment by MakhouT** [comment]
Hi guys,

I am still having issues, while Medusa just got updated to version 0.3.11
@medariox I'm adding logs as requested

```
2020-02-01 22:56:42 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: [9a36461] No needed episodes found during backlog search for: Boku no Hero Academia
2020-02-01 22:56:42 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: AlphaRatio :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: TorrentLeech :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: Nyaa :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: [9a36461] Using backlog search providers
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: [9a36461] Building internal name cache for Boku no Hero Academia
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: [9a36461] Finished processing 3209 scene exceptions.
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: [9a36461] Updating exception_cache and exception_season_cache
2020-02-01 22:56:41 INFO	FORCEDSEARCHQUEUE-BACKLOG-13615 :: [9a36461] Beginning backlog search for: Boku no Hero Academia
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Unable to find manual results for: Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Using manual search providers
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Building internal name cache for Boku no Hero Academia
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Finished processing 3209 scene exceptions.
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Updating exception_cache and exception_season_cache
2020-02-01 22:53:32 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Beginning manual search for: Boku no Hero Academia - S04E16 - Win Those Kids' Hearts```

```
Branch: master
Commit: 9a364616d1bc7bed025f3c08270ac993cfa0c046
Version: 0.3.11
```

![image](https://user-images.githubusercontent.com/3041165/73599714-be3e4280-4546-11ea-993d-42f5fcea8f93.png)

If you need more details, please let me know. Happy to provide more if needed. Would you please be able to have a look?

Thanks!

**Comment by medariox** [comment]
You need to post **debug** logs of a **manual** search and **debug** logs. Make sure to restart Medusa before you do that.

**Comment by MakhouT** [comment]
Hi,

I just restarted Medusa

And I think I did a manual search again 
(it's this icon, right?
![image](https://user-images.githubusercontent.com/3041165/73600149-acf83480-454c-11ea-8b3c-a26c93a89146.png)

)

```
2020-02-01 23:39:28 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Unable to find manual results for: Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] 13615: Formatting pattern: %SN - S%0SE16 - %EN -> Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Found 0 unique search results
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Data returned from provider does not contain any torrents
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] GET URL: https://alpharatio.cc/torrents.php?searchstr=Boku+no+Hero+Academia+00&filter_cat%5B1%5D=1&filter_cat%5B5%5D=1&filter_cat%5B2%5D=1&filter_cat%5B4%5D=1&filter_cat%5B3%5D=1 [Status: 200]
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Search string: Boku no Hero Academia 00
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Search mode: Episode
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] GET URL: https://alpharatio.cc/index.php [Status: 200]
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] With post data: password=**********&login=submit&username=**********&remember_me=on
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:28 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] POST URL: https://alpharatio.cc/login.php [Status: 302]
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Could not find any candidates in cache, searching provider.
2020-02-01 23:39:27 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Found 0 unique search results
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Data returned from provider does not contain any torrents
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] GET URL: https://www.torrentleech.org/torrents/browse/list/categories/35,26,32,44,34/query/Boku%20no%20Hero%20Academia%2000/orderby/seeders/order/desc/ [Status: 200]
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Search string: Boku no Hero Academia 00
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Search mode: Episode
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] GET URL: https://www.torrentleech.org/ [Status: 200]
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] With post data: password=**********&login=submit&username=**********&remember_me=on
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] POST URL: https://www.torrentleech.org/user/account/login [Status: 302]
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Could not find any candidates in cache, searching provider.
2020-02-01 23:39:27 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Found 0 unique search results
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Discarding torrent because it doesn't meet the minimum seeders: [RH] Boku no Hero Academia S2 - 00-06 v2 [English Dubbed] [1080p]. Seeders: 0
2020-02-01 23:39:27 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Discarding torrent because it doesn't meet the minimum seeders: [PuyaSubs!] Boku no Hero Academia 3 - 41 [720p][0025E3AC].mkv. Seeders: 0
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] GET URL: https://nyaa.si/?page=rss&f=2&c=1_0&q=Boku+no+Hero+Academia+00 [Status: 200]
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Search string: Boku no Hero Academia 00
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Searching only confirmed torrents
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Search mode: Episode
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Could not find any candidates in cache, searching provider.
2020-02-01 23:39:25 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 23:39:25 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Using manual search providers
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Internal name cache for boku no hero academia set to: boku no hero academia
2020-02-01 23:39:25 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Building internal name cache for Boku no Hero Academia
2020-02-01 23:39:25 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Finished processing 3209 scene exceptions.
2020-02-01 23:39:25 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Updating exception_cache and exception_season_cache
2020-02-01 23:39:25 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Beginning manual search for: Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 23:39:25 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] 13615: Formatting pattern: %SN - S%0SE16 - %EN -> Boku no Hero Academia - S04E16 - Win Those Kids' Hearts```

**Comment by medariox** [comment]
Yes, you have to enable scene numbering for this show or it won't find anything with the indexer numbering (it is initially enabled by default).

**Comment by MakhouT** [comment]
I enabled it and I still can't seem to find it
![image](https://user-images.githubusercontent.com/3041165/73600227-7373f900-454d-11ea-9ff0-2dfae9604f3a.png)

```
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Unable to find manual results for: Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] 13615: Formatting pattern: %SN - S%0SE16 - %EN -> Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Found 0 unique search results
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Data returned from provider does not contain any torrents
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] GET URL: https://alpharatio.cc/torrents.php?searchstr=Boku+no+Hero+Academia+00&filter_cat%5B1%5D=1&filter_cat%5B5%5D=1&filter_cat%5B2%5D=1&filter_cat%5B4%5D=1&filter_cat%5B3%5D=1 [Status: 200]
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Search string: Boku no Hero Academia 00
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Search mode: Episode
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Could not find any candidates in cache, searching provider.
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: AlphaRatio :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Found 0 unique search results
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Data returned from provider does not contain any torrents
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] GET URL: https://www.torrentleech.org/torrents/browse/list/categories/35,26,32,44,34/query/Boku%20no%20Hero%20Academia%2000/orderby/seeders/order/desc/ [Status: 200]
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Search string: Boku no Hero Academia 00
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Search mode: Episode
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] GET URL: https://www.torrentleech.org/ [Status: 200]
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] With post data: password=**********&login=submit&username=**********&remember_me=on
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] POST URL: https://www.torrentleech.org/user/account/login [Status: 302]
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Could not find any candidates in cache, searching provider.
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: TorrentLeech :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Found 0 unique search results
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Discarding torrent because it doesn't meet the minimum seeders: [RH] Boku no Hero Academia S2 - 00-06 v2 [English Dubbed] [1080p]. Seeders: 0
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Discarding torrent because it doesn't meet the minimum seeders: [PuyaSubs!] Boku no Hero Academia 3 - 41 [720p][0025E3AC].mkv. Seeders: 0
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] User-Agent: Medusa/0.3.11 (Linux; 4.15.0-62-generic; 6a5097d4-4543-11ea-b95f-0cc47abb5400)
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] GET URL: https://nyaa.si/?page=rss&f=2&c=1_0&q=Boku+no+Hero+Academia+00 [Status: 200]
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Search string: Boku no Hero Academia 00
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Searching only confirmed torrents
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Search mode: Episode
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Could not find any candidates in cache, searching provider.
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: Nyaa :: [9a36461] Performing episode search for Boku no Hero Academia
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Using manual search providers
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Internal name cache for boku no hero academia set to: boku no hero academia
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Building internal name cache for Boku no Hero Academia
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Finished processing 3209 scene exceptions.
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Updating exception_cache and exception_season_cache
2020-02-01 23:49:35 INFO	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] Beginning manual search for: Boku no Hero Academia - S04E16 - Win Those Kids' Hearts
2020-02-01 23:49:35 DEBUG	FORCEDSEARCHQUEUE-MANUAL-13615 :: [9a36461] 13615: Formatting pattern: %SN - S%0SE16 - %EN -> Boku no Hero Academia - S04E16 - Win Those Kids' Hearts```

Am I doing something wrong?
Is it working for you?

**Comment by medariox** [comment]
Disable only confirmed torrents for Nyaa.

**Comment by medariox** [comment]
Also you need to add animes with thetvdb indexer, did you do that?

**Comment by MakhouT** [comment]
I Just adjust my Nyaa settings
![image](https://user-images.githubusercontent.com/3041165/73600392-c353bf80-454f-11ea-8fb6-8070a2d0ca6f.png)
But I was expecting it to find it on HorribleSubs before as it's higher in my providers lists.

Because I don't remember with which indexer, I've added boku no hero academia, I just deleted it and tried adding it again.
But thetvdb indexer wasn't listed
![image](https://user-images.githubusercontent.com/3041165/73600405-ef6f4080-454f-11ea-80d6-37ec1c439355.png)


Then I tried searching for it in it's English term 'My hero academia'
![image](https://user-images.githubusercontent.com/3041165/73600441-76bcb400-4550-11ea-9466-a519f453458f.png)

And now I've done a manual search 
![image](https://user-images.githubusercontent.com/3041165/73600449-8dfba180-4550-11ea-8a75-0c78ce475bcf.png)

And I can find the results! That's a step forward for me!
I can still only find nyaa though, so I'll check why it's not finding horriblesubs.

Also it seems it's not mapping correctly the season episodes to the absolute scene numbers
![image](https://user-images.githubusercontent.com/3041165/73600488-ec288480-4550-11ea-8f7d-c12b0c9954f7.png)


Thank you for the support medariox. I am happy I am already a right step in the correct direction.

**Comment by medariox** [comment]
Do you have scene numbering enabled?

**Comment by MakhouT** [comment]
Yes I do,
Screenshot to confirm
![Screenshot_20200202-010251](https://user-images.githubusercontent.com/3041165/73600917-19c4fc00-4558-11ea-8b0f-b677fe0257fa.jpg)

**Comment by medariox** [comment]
Not sure what to tell you. Working fine here with the same settings.

**Comment by p0psicles** [comment]
You don't need scene numbering for this show. Try disabling that and restart just to be sure .
