### ISSUE TITLE
can't list shows, TypeError('an integer is required (got type NoneType)',)

### ISSUE THREAD

**Issue by jfgsystems** [pymedusa/Medusa#8412]
since updating to 0.4.1 the show list no longer works. when attempting to list shows the following error appears in the logs. I've also tried reducing the number of shows returned to 1 and the same error occurs. 

2020-08-28 14:28:30 ERROR    TORNADO :: [20915b5] Uncaught exception in APIv2: TypeError('an integer is required (got type NoneType)',)
Request: GET /sickrage/api/v2/series?limit=1000&page=1 (192.168.xx.xx)
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/series.py", line 56, in get
    for s in Series.find_series(predicate=filter_series)
  File "/opt/medusa/medusa/server/api/v2/series.py", line 56, in <listcomp>
    for s in Series.find_series(predicate=filter_series)
  File "/opt/medusa/medusa/tv/series.py", line 2124, in to_json
    data['lastUpdate'] = datetime.date.fromordinal(self._last_update_indexer).isoformat()
TypeError: an integer is required (got type NoneType)

ubuntu 18.04
python 3.6.9

edit: switched to python 3.7.5, no change

**Comment by medariox** [comment]
There is an issue with your `main.db`. Can you upload it to https://catdrop.drycat.fr/ (or any free service you like) and share the link?

**Comment by jfgsystems** [comment]
here's a link to it: https://mega.nz/file/S08zARDS#61wRbIoFKGPjHQwNrX1EEm0lO_7bu9DtVzxxs1Ndpr8

I notice 'mass update' seems to list all the shows just fine

**Comment by medariox** [comment]
Thanks! For some reason 3 of your shows were not added correctly. I've fixed the DB manually and will push a fix that prevents this issue from occurring again. 

In the meanwhile, you can download the fixed DB from here: https://catdrop.drycat.fr/r/NsZVXvIk#BDgWCPXezza4XWI8ohi0ah0s33jQmaQQOxmKaxQQvvE=

**Comment by jfgsystems** [comment]
Thank you for the assistance, it's working properly now

**Comment by medariox** [comment]
Since you are the only one reporting this issue I will wait to push the fix, as this issue should actually never occur.

**Comment by jeffgus** [comment]
I also have this issue. I checked out an older release from git so it would work. Today I decided to go back to master and the issue still exists. 

Would anyone describe the fix for the main.db? I can use sqlite myself to fix it if I have the info. I tried grabbing the files attached, but they've since been removed.

**Comment by jeffgus** [comment]
It appears I fixed it. In my case I did this:
update tv_shows set last_update_indexer=737710 where last_update_indexer IS NULL;
